sudo: required
dist: bionic
language: cpp

env:
  global:
    - DEPS_DIR=${HOME}/deps

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-8
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
      env:
      - VCPKG_TRIPLET=x64-linux
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8

install:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}
  - |
    set -e
    mkdir -p ${DEPS_DIR}/vcpkg
    pushd ${DEPS_DIR}/vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin master
    git checkout -b master origin/master
    ./bootstrap-vcpkg.sh
    git apply ${OLDPWD}/src/vcpkg_patch.diff
    echo -e '\nset(VCPKG_BUILD_TYPE release)' >> ./triplets/${VCPKG_TRIPLET}.cmake
    ./vcpkg install glad glfw3 imgui
    popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DBUILD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
