sudo: required
dist: bionic
language: cpp

env:
  global:
    - DEPS_DIR=${HOME}/deps

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      env:
      - VCPKG_TRIPLET=x64-linux
      - C_COMPILER=gcc-9
      - CXX_COMPILER=g++-9

install:
  - |
    set -e
    mkdir -p ${DEPS_DIR}/vcpkg
    pushd ${DEPS_DIR}/vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin master
    git checkout -b master origin/master
    ./bootstrap-vcpkg.sh
    git apply ${OLDPWD}/src/vcpkg_patch.diff
    ./vcpkg install glad glfw3 imgui
    popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

script:
  - cmake --version
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DBUILD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - make -j `nproc` install
