sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-8
            - valgrind
            - libglfw3-dev
      env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8

install:
  - |
    set -e
    git clone https://github.com/Microsoft/vcpkg.git ${DEPS_DIR}/vcpkg
    pushd ${DEPS_DIR}/vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg install glad:x86-linux glad:x64-linux glfw3:x86-linux glfw3:x64-linux imgui:x86-linux imgui:x64-linux
    popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

script:
  - cmake --version
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DBUILD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - make -j `nproc` install
