sudo: required
dist: bionic
language: cpp

env:
  global:
    - DEPS_DIR=${HOME}/deps

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      env:
      - VCPKG_TRIPLET=x64-linux
      - C_COMPILER=gcc-9
      - CXX_COMPILER=g++-9

install:
  - |
    set -e
    echo "test 1"
    if [ ! -d ${DEPS_DIR}/vcpkg ]
    then
        echo "test 2"
        pushd ${DEPS_DIR}/vcpkg
        echo "test 3"
        git clone https://github.com/Microsoft/vcpkg.git ${DEPS_DIR}/vcpkg
        echo "test 4"
        ./bootstrap-vcpkg.sh
        echo "test 5"
        popd
    fi
    pushd ${DEPS_DIR}/vcpkg
    echo "test 6"
    pwd
    ls -al
    git pull
    echo "test 7"
    git apply ${OLDPWD}/src/vcpkg_patch.diff
    echo "test 8"
    echo -e '\nset(VCPKG_BUILD_TYPE release)' >> ./triplets/${VCPKG_TRIPLET}.cmake
    echo "test 9"
    ./vcpkg install glad glfw3 imgui
    echo "test 10"
    popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

script:
  - cmake --version
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DBUILD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - make -j `nproc` install
